export const AuditEvents = {
  // Authentication
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_REFRESH: 'AUTH_REFRESH',
  AUTH_REFRESH_REUSE: 'AUTH_REFRESH_REUSE',
  AUTH_SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  
  // Authorization
  AUTHZ_DENIED: 'AUTHZ_DENIED',

  // Impersonation
  IMPERSONATION_STARTED: 'IMPERSONATION_STARTED',
  IMPERSONATION_ENDED: 'IMPERSONATION_ENDED',
  IMPERSONATION_EXPIRED: 'IMPERSONATION_EXPIRED',
  IMPERSONATION_DENIED: 'IMPERSONATION_DENIED',

  // Tenant Admin
  TENANT_CREATED: 'TENANT_CREATED',
  TENANT_UPDATED: 'TENANT_UPDATED',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  TENANT_REACTIVATED: 'TENANT_REACTIVATED',
  TENANT_DELETED: 'TENANT_DELETED',

  // User Management
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DISABLED: 'USER_DISABLED',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',

  // Core CRM
  LEAD_CREATED: 'LEAD_CREATED',
  LEAD_UPDATED: 'LEAD_UPDATED',
  LEAD_DELETED: 'LEAD_DELETED',
  LEAD_ASSIGNED: 'LEAD_ASSIGNED',
  LEAD_REASSIGNED: 'LEAD_REASSIGNED',
  LEAD_STAGE_CHANGED: 'LEAD_STAGE_CHANGED',
  CALL_CREATED: 'CALL_CREATED',
  MESSAGE_CREATED: 'MESSAGE_CREATED',
  TICKET_CREATED: 'TICKET_CREATED',
  TICKET_UPDATED: 'TICKET_UPDATED',
  CSV_BULK_IMPORT: 'CSV_BULK_IMPORT',
  BULK_LEAD_UPDATE: 'BULK_LEAD_UPDATE',
  AUDIO_TRANSCRIBED: 'AUDIO_TRANSCRIBED',

  // Compliance
  COMPLIANCE_POLICY_UPDATED: 'COMPLIANCE_POLICY_UPDATED',
  COMPLIANCE_DENIED: 'COMPLIANCE_DENIED',
  CONTACT_OPT_OUT: 'CONTACT_OPT_OUT',
  CONTACT_DNC: 'CONTACT_DNC',

  // Exports
  DATA_EXPORT_REQUESTED: 'DATA_EXPORT_REQUESTED',
  DATA_EXPORT_COMPLETED: 'DATA_EXPORT_COMPLETED',
  DATA_EXPORT_DENIED: 'DATA_EXPORT_DENIED',

  // Admin & Settings
  CUSTOM_FIELDS_UPDATED: 'CUSTOM_FIELDS_UPDATED',
  ROLE_PERMISSIONS_UPDATED: 'ROLE_PERMISSIONS_UPDATED',
  PIPELINE_CONFIG_UPDATED: 'PIPELINE_CONFIG_UPDATED',
  AUTO_ASSIGNMENT_TOGGLED: 'AUTO_ASSIGNMENT_TOGGLED',

  // Security Operations
  SECURITY_ALERT_CREATED: 'SECURITY_ALERT_CREATED',
  SECURITY_ALERT_RESOLVED: 'SECURITY_ALERT_RESOLVED',
  
  INVOICE_PAID: 'INVOICE_PAID',
  FEATURE_FLAG_UPDATED: 'FEATURE_FLAG_UPDATED',

  // Fallback / Unknown
  UNKNOWN_EVENT: 'UNKNOWN_EVENT'
} as const;

export type AuditEventType = keyof typeof AuditEvents;

export const AuditOutcomes = {
  SUCCESS: 'SUCCESS',
  DENIED: 'DENIED',
  FAILURE: 'FAILURE',
  EXPIRED: 'EXPIRED',
  REVOKED: 'REVOKED'
} as const;

export type AuditOutcome = keyof typeof AuditOutcomes;
